spring.jackson.default-property-inclusion=NON_NULL
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=app.log
spring.application.name=civicdraft
spring.datasource.url=jdbc:postgresql://localhost:5432/khtml_draft
spring.datasource.username=postgres
spring.datasource.password=P(sjs837483)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8084
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.kr.ddm.civic=DEBUG

